Added steps for installing opa in container file and updated README
ploigos/ploigos-containers pull request #70
Opened 2021-07-06 21:31 UTC by jthompkins

Adding container file for automated governance image that contains both rekor and opa.

2021-07-06 21:40 UTC, gfulton-redhat requested changes
@jthompkins you also need to update the README with a section that describes `ploigos-tool-autogov`.

2021-07-06 21:40 UTC, gfulton-redhat commented on ploigos-tool-autogov/Containerfile.ubi8
> +    com.redhat.component="ploigos-tool-rekor-container"
The component should reference `ploigos-tool-autogov`?

```suggestion
    com.redhat.component="ploigos-tool-autogov"
```

2021-07-06 21:44 UTC, gfulton-redhat commented on ploigos-tool-autogov/Containerfile.ubi8
> +    io.openshift.tags="ploigos,rekor" \
```suggestion
    io.openshift.tags="ploigos,autogov" \
```

2021-07-06 21:44 UTC, gfulton-redhat commented on ploigos-tool-autogov/Containerfile.ubi8
> +    com.redhat.component="ploigos-tool-rekor-container"
```suggestion
    com.redhat.component="ploigos-tool-autogov"    
```

2021-07-06 21:53 UTC, jthompkins commented on ploigos-tool-autogov/Containerfile.ubi8
> +    com.redhat.component="ploigos-tool-rekor-container"
Changed

2021-07-06 21:53 UTC, jthompkins commented on ploigos-tool-autogov/Containerfile.ubi8
> +    io.openshift.tags="ploigos,rekor" \
Changed

2021-07-06 22:02 UTC, gfulton-redhat submitted a review, later dismissed

2021-07-06 22:42 UTC, itewk requested changes

2021-07-06 22:42 UTC, itewk commented on README.md
>  ## ploigos-tool-rekor
as talked about, nuke the rekor image and we will jut have the autogov image going forward

2021-07-06 22:42 UTC, itewk commented on README.md
> +* ploigos-tool-rekor
as talked about, nuke the rekor image and we will jut have the autogov image going forward

2021-07-06 22:42 UTC, itewk commented on README.md
>  podman build --tag ploigos-tool-rekor       --build-arg BASE_IMAGE=ploigos-base            ploigos-tool-rekor
as talked about, nuke the rekor image and we will jut have the autogov image going forward

2021-07-07 12:02 UTC, itewk requested changes

2021-07-07 12:02 UTC, itewk commented on .github/workflows/publish.yaml
> +          echo "Check opa binary exists"
merge this into the previous test image step, rather then having multiple steps just do all the calls one after the other.

2021-07-07 12:02 UTC, itewk commented on ploigos-tool-autogov/Containerfile.ubi8
> +
nit: remove extra new line

2021-07-07 12:02 UTC, itewk commented on ploigos-tool-autogov/README.md
> +This repository contains the container definition for creating the Ploigos tool for running rekor and opa commands.
nit: id rephrase this to say "this repoisotry contains the container definition for creating the Ploigos tools container for performing auto governance oeprations. Included tools are:
* rekor
* opa

2021-07-07 12:02 UTC, itewk commented on ploigos-tool-autogov/contrib/centos.repo
> +[centos]
@jthompkins what is this needed for?

2021-07-07 17:09 UTC, jthompkins commented on ploigos-tool-autogov/contrib/centos.repo
> +[centos]
I am not sure actually. I copied the ploigos-tool-rekor directory as a starting point and it had this file already

2021-07-07 17:19 UTC, jthompkins commented on README.md
>  ## ploigos-tool-rekor
Nuked.

2021-07-07 17:19 UTC, jthompkins commented on README.md
> +* ploigos-tool-rekor
Nuked.

2021-07-07 17:20 UTC, jthompkins commented on README.md
>  podman build --tag ploigos-tool-rekor       --build-arg BASE_IMAGE=ploigos-base            ploigos-tool-rekor
Nuked.

2021-07-07 17:20 UTC, jthompkins commented on .github/workflows/publish.yaml
> +          docker run -u 1001 --entrypoint='' ${{ env.IMAGE_TAG_LOCAL }} /bin/sh -c "rekor --help"
Fixed.

2021-07-07 17:20 UTC, jthompkins commented on .github/workflows/publish.yaml
> +          echo "Check opa binary exists"
Fixed.

2021-07-07 17:20 UTC, jthompkins commented on ploigos-tool-autogov/Containerfile.ubi8
> +
Fixed.

2021-07-12 21:24 UTC, itewk approved these changes

2021-07-12 21:24 UTC, merged